--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t quay.io/escriche/2048-logicalis-game ."
      - "docker tag quay.io/escriche/2048-logicalis-game quay.io/escriche/2048-logicalis-game:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push quay.io/escriche/2048-logicalis-game:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login"
version: 0.1
